name = "heyform"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# Static Assets: serves the HeyForm React webapp
[assets]
directory = "../webapp/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Cloudflare D1 Database
[[d1_databases]]
binding = "DB"
database_name = "heyform-db"
database_id = "55bb9dd8-18f2-426c-868f-b49087440ffb"

# Optional Cloudflare R2 Bucket for file uploads
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "heyform-uploads"

[vars]
SESSION_SECRET = "9f8e43cb12a5df6790b4e28c31d57e84ab6123cd48ef01923a756b1049c8321e"
APP_DISABLE_REGISTRATION = "false"
